# Generated by Django 3.0 on 2020-01-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalComment',
        ),
    ]
