# Generated by Django 3.0 on 2020-02-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_additionalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
