# Generated by Django 3.0 on 2020-02-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200222_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_subject', models.CharField(max_length=220, verbose_name='Название предмета')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
        ),
    ]
