# Generated by Django 3.0 on 2020-02-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200223_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['teacher'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='is_teacher',
        ),

    ]
