# Generated by Django 3.0 on 2020-02-24 14:04

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200224_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.utilities.get_timestamp_path, verbose_name='Материал')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Дополнительный материал',
                'verbose_name_plural': 'Дополнительные материалы',
            },
        ),
    ]
