# Generated by Django 3.0 on 2020-02-25 12:42

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_additionalfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfile',
            name='file',
            field=models.FileField(upload_to=main.utilities.get_namestamp_path, verbose_name='Материал'),
        ),
    ]
