# Generated by Django 3.0 on 2020-02-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200225_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_student',
        ),
    ]
