# Generated by Django 3.0 on 2020-03-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200304_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Звание'),
        ),
    ]
