# Generated by Django 3.0 on 2020-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200304_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(blank=True, max_length=40, verbose_name='Звание'),
        ),
    ]
