# Generated by Django 3.0 on 2020-03-15 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200316_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SubGroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель'),
        ),
    ]
