# Generated by Django 3.0 on 2020-03-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200316_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SubGroup', verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
