# Generated by Django 3.0 on 2020-03-16 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200316_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Schedule', verbose_name='Расписание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
