# Generated by Django 3.0 on 2020-03-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_additionalschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalschedule',
            options={'verbose_name': 'Продолжение расписания', 'verbose_name_plural': 'Продолжение расписания'},
        ),
    ]
