# Generated by Django 3.0 on 2020-03-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200316_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject', verbose_name='Дисциплина'),
        ),
    ]
