# Generated by Django 3.0 on 2020-03-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200316_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalschedule',
            name='teacher',
            field=models.ForeignKey(default='Преподаватель не указан', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Teacher', verbose_name='Преподаватель'),
        ),
    ]
