# Generated by Django 3.0 on 2020-03-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200316_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalschedule',
            name='auditory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Auditory', verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='additionalschedule',
            name='days',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], max_length=1, null=True, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='additionalschedule',
            name='start_time',
            field=models.TimeField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], max_length=6, null=True, verbose_name='Начало занятия'),
        ),
        migrations.AddField(
            model_name='additionalschedule',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Structure', verbose_name='Учебный корпус'),
        ),
    ]
