# Generated by Django 3.0 on 2020-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200316_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalschedule',
            name='days',
            field=models.CharField(choices=[('08:30', '08:30'), ('10:25', '10:25'), ('12:35', '12:35'), ('14:30', '14:30'), ('16:25', '16:25'), ('18:10', '18:10')], max_length=6, null=True, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='start_time',
            field=models.TimeField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], max_length=1, null=True, verbose_name='Начало занятия'),
        ),
    ]
