# Generated by Django 3.0 on 2020-03-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200316_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalschedule',
            old_name='days',
            new_name='day',
        ),
    ]
