# Generated by Django 3.0 on 2020-04-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200317_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name_of_subject'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='additionalschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubGroup', verbose_name='Группа'),
        ),
    ]
