# Generated by Django 3.0.2 on 2020-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200404_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
